edited by: Roberto Sanchez and Ahmed Abdelhay

Script started on Mon 26 Sep 2011 10:20:05 PM EDT
bash-3.2$ cd ~/os161/root/
bash-3.2$ sys161 kernel
sys161: System/161 release 1.14, compiled Aug 24 2011 10:55:58


OS/161 base system version 1.11
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Roberto_Sanchez system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
336k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: ?

OS/161 kernel menu
    [?o] Operations menu                [kh] Kernel heap stats              
    [?t] Tests menu                     [q] Quit and shut down              

Operation took 0.021540000 seconds
OS/161 kernel [? for menu]: ?o

OS/161 operations menu
    [s]       Shell                     [cd]      Change directory          
    [p]       Other program             [pwd]     Print current directory   
    [mount]   Mount a filesystem        [sync]    Sync filesystems          
    [unmount] Unmount a filesystem      [panic]   Intentional panic         
    [bootfs]  Set "boot" filesystem     [q]       Quit and shut down        
    [pf]      Print a file              

Operation took 0.055721200 seconds
OS/161 kernel [? for menu]: ?t

OS/161 tests menu
    [at]  Array test                    [sy1] Semaphore test                
    [bt]  Bitmap test                   [sy2] Lock test             (1)     
    [qt]  Queue test                    [sy3] CV test               (1)     
    [km1] Kernel malloc test            [fs1] Filesystem test               
    [km2] kmalloc stress test           [fs2] FS read stress        (4)     
    [tt1] Thread test 1                 [fs3] FS write stress       (4)     
    [tt2] Thread test 2                 [fs4] FS write stress 2     (4)     
    [tt3] Thread test 3                 [fs5] FS create stress      (4)     

    (1) These tests will fail until you finish the synch assignment.
    (4) These tests will fail until you finish the file system assignment.

Operation took 0.096676520 seconds
OS/161 kernel [? for menu]: kh
Subpage allocator status:
at 0x80030000: size 64    61/64 free
   .............................................................***
at 0x8002f000: size 512   7/8 free
   .......*
at 0x8002e000: size 32    106/128 free
   ................................................................
   ..........................................**********************
at 0x8002d000: size 128   30/32 free
   ..............................**
at 0x8002c000: size 16    196/256 free
   ................................................................
   ................................................................
   ................................................................
   ....************************************************************
Operation took 0.053740000 seconds
OS/161 kernel [? for menu]: q
Shutting down.
The system is halted.
sys161: 1020676342 cycles (14632724k, 0u, 1006043618i)

sys161: 6305 irqs 0 exns 0r/0w disk 13r/3020w console 0r/0w/1m emufs 0r/0w net

sys161: Elapsed real time: 40.777866 seconds (25.0302 mhz)

sys161: Elapsed virtual time: 40.827053680 seconds (25 mhz)

bash-3.2$ exit
exit

Script done on Mon 26 Sep 2011 10:21:17 PM EDT
